export const SAVE_NAVBAR_OPTION = "SAVE_NAVBAR_OPTION";
export const SAVE_NAVBAR_OPTION_SUCCESSFUL = "SAVE_NAVBAR_OPTION_SUCCESSFUL";
export const SAVE_NAVBAR_OPTION_FAILED = "SAVE_NAVBAR_OPTION_FAILED";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";