export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
export const FETCH_SEARCH_RESULTS_SUCCESSFUL = "FETCH_SEARCH_RESULTS_SUCCESSFUL";
export const FETCH_SEARCH_RESULTS_FAILED = "FETCH_SEARCH_RESULTS_FAILED";
export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_TRENDING_SUCCESSFUL = "FETCH_TRENDING_SUCCESSFUL";
export const FETCH_TRENDING_FAILED = "FETCH_TRENDING_FAILED";