export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
export const FETCH_SEARCH_RESULTS_SUCCESSFUL = "FETCH_SEARCH_RESULTS_SUCCESSFUL";
export const FETCH_SEARCH_RESULTS_FAILED = "FETCH_SEARCH_RESULTS_FAILED";