export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_DETAILS_SUCCESSFUL = "FETCH_MOVIE_DETAILS_SUCCESSFUL";
export const FETCH_MOVIE_DETAILS_FAILED = "FETCH_MOVIE_DETAILS_FAILED";
export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
export const FETCH_MOVIE_CREDITS_SUCCESSFUL = "FETCH_MOVIE_CREDITS_SUCCESSFUL";
export const FETCH_MOVIE_CREDITS_FAILED = "FETCH_MOVIE_CREDITS_FAILED";
export const FETCH_MOVIE_REVIEWS = "FETCH_MOVIE_REVIEWS";
export const FETCH_MOVIE_REVIEWS_SUCCESSFUL = "FETCH_MOVIE_REVIEWS_SUCCESSFUL";
export const FETCH_MOVIE_REVIEWS_FAILED = "FETCH_MOVIE_REVIEWS_FAILED";
export const FETCH_SIMILAR_MOVIES = "FETCH_SIMILAR_MOVIES";
export const FETCH_SIMILAR_MOVIES_SUCCESSFUL =
	"FETCH_SIMILAR_MOVIES_SUCCESSFUL";
export const FETCH_SIMILAR_MOVIES_FAILED = "FETCH_SIMILAR_MOVIES_FAILED";
export const SAVE_WATCHLIST_MOVIE = "SAVE_WATCHLIST_MOVIE";
export const SAVE_WATCHLIST_MOVIE_SUCCESSFUL =
	"SAVE_WATCHLIST_MOVIE_SUCCESSFUL";
export const SAVE_WATCHLIST_MOVIE_FAILED = "SAVE_WATCHLIST_MOVIE_FAILED";
export const SAVE_FAVOURITE_MOVIE = "SAVE_FAVOURITE_MOVIE";
export const SAVE_FAVOURITE_MOVIE_SUCCESSFUL =
	"SAVE_FAVOURITE_MOVIE_SUCCESSFUL";
export const SAVE_FAVOURITE_MOVIE_FAILED = "SAVE_FAVOURITE_MOVIE_FAILED";
export const FETCH_IS_MOVIE_SAVED = "FETCH_IS_MOVIE_SAVED";
export const FETCH_IS_MOVIE_SAVED_SUCCESSFUL = "FETCH_IS_MOVIE_SAVED_SUCCESSFUL";
export const FETCH_IS_MOVIE_SAVED_FAILED = "FETCH_IS_MOVIE_SAVED_FAILED";
