export const FETCH_PERSON_DETAILS = "FETCH_PERSON_DETAILS";
export const FETCH_PERSON_DETAILS_SUCCESSFUL = "FETCH_PERSON_DETAILS_SUCCESSFUL";
export const FETCH_PERSON_DETAILS_FAILED = "FETCH_PERSON_DETAILS_FAILED";
export const FETCH_PERSON_MOVIES = "FETCH_PERSON_MOVIES";
export const FETCH_PERSON_MOVIES_SUCCESSFUL = "FETCH_PERSON_MOVIES_SUCCESSFUL";
export const FETCH_PERSON_MOVIES_FAILED = "FETCH_PERSON_MOVIES_FAILED";