export const FETCH_POPULAR_TV_SHOWS = "FETCH_POPULAR_TV_SHOWS";
export const FETCH_POPULAR_TV_SHOWS_SUCCESSFUL = "FETCH_POPULAR_TV_SHOWS_SUCCESSFUL";
export const FETCH_POPULAR_TV_SHOWS_FAILED = "FETCH_POPULAR_TV_SHOWS_FAILED";
export const FETCH_TOP_RATED_TV_SHOWS = "FETCH_TOP_RATED_TV_SHOWS";
export const FETCH_TOP_RATED_TV_SHOWS_SUCCESSFUL = "FETCH_TOP_RATED_TV_SHOWS_SUCCESSFUL";
export const FETCH_TOP_RATED_TV_SHOWS_FAILED = "FETCH_TOP_RATED_TV_SHOWS_FAILED";