export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const FETCH_UPCOMING_MOVIES_SUCCESSFUL = "FETCH_UPCOMING_MOVIES_SUCCESSFUL";
export const FETCH_UPCOMING_MOVIES_FAILED = "FETCH_UPCOMING_MOVIES_FAILED";